
post_install()
{
    echo "----------------------------------------------------------------"
    echo "To enable leosac deamon run these commands as root:"
    echo "systemctl enable leosacd"
    echo "systemctl start leosacd"
    echo ""
    echo "More info here:"
    echo "https://github.com/islog/leosac/wiki"
    echo "----------------------------------------------------------------"
}

post_upgrade()
{
    echo "----------------------------------------------------------------"
    echo "To restart leosac deamon run this command as root:"
    echo "systemctl restart leosacd"
    echo ""
    echo "More info here:"
    echo "https://github.com/islog/leosac/wiki"
    echo "----------------------------------------------------------------"
}
