#!/bin/sh

echo "----------------------------------------------------------------"
echo "To enable leosac daemon run these commands as root:"
echo "systemctl enable leosacd"
echo "systemctl start leosacd"
echo ""
echo "To disable, run as root:"
echo "systemctl stop leosacd"
echo "systemctl disable leosacd"
echo ""
echo "More info here:"
echo "https://www.leosac.com/"
echo "----------------------------------------------------------------"

#DEBHELPER#

