#!/bin/sh

echo "----------------------------------------------------------------"
echo "To enable leosac daemon run these commands as root:"
echo "systemctl enable leosac"
echo "systemctl start leosac"
echo ""
echo "To disable, run as root:"
echo "systemctl stop leosac"
echo "systemctl disable leosac"
echo ""
echo "More info here:"
echo "https://www.leosac.com/"
echo "----------------------------------------------------------------"

#DEBHELPER#

