# maxhy/leosac-buildsystem
FROM debian:sid
ARG TARGETPLATFORM

VOLUME /usr/src/leosac/leosac
VOLUME /tmp/leosac

RUN apt-get update && apt-get install -y          \
cmake build-essential pkg-config git              \
apt-utils libssl-dev libzmq5 libzmq3-dev          \
libcurl4-openssl-dev libtclap-dev libscrypt-dev   \
python3 python3-pip gcc g++                       \
dh-make dpkg-dev debhelper devscripts             \
libboost-all-dev libgtest-dev emacs-nox vim wget  \
libsqlite3-dev libpq-dev odb libgpiod-dev

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 2 && \
pip3 install pyzmq --break-system-packages

# Enable sudo without password
RUN echo '%adm ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

RUN export TARGETPLATFORM
