on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - name: Build
        if: success()
        run: |
          docker buildx build --tag maxhy/leosac:edge \
            --platform linux/amd64 \
            --build-arg VERSION=edge \
            --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
            --build-arg VCS_REF=${GITHUB_SHA::8} \
            -f docker/Dockerfile.main .
      - name: Inspect image
        run: |
          docker buildx imagetools inspect maxhy/leosac:edge
      - run: mkdir /build
      - name: Run linux/amd64
        if: success()
        run: docker run --platform linux/amd64 -v /build:/tmp/leosac maxhy/leosac:edge
      - uses: actions/upload-artifacts@v3
        if: success()
        with:
          name: Deb files
          path: /build/*.deb
